### PR TITLE
FreeBSD requires sin_len field to be set.

### PR DESCRIPTION
**Pull request by vlm**
Otherwise e.g. valgrind complains.

### CODE REVIEW

**Comment by sustrik** [comment]
Is this causing problems?

AFAIU this field is not required to be set, see here:

http://stackoverflow.com/questions/38913326/are-sockaddr-in-and-sockaddr-in6-still-using-sin-len-and-sin6-len

**Comment by vlm** [comment]
Valgrind complains if it is not set properly. Also, older versions of freebsd wouldn't work, and afair solaris, too.

-- 
Lev

**Comment by sustrik** [comment]
Fair enough. Thanks for the patch!

**Comment by vlm** [comment]
Yeah, if you noticed there's a provision for setting the sin_len in the DNS library (the `#if defined(SA_LEN)` which I've extended), but it wasn't consistently applied.

**Comment by vlm** [comment]
Also, https://github.com/wahern/dns/pull/21

**Pull request merged**
