### PR TITLE
Threadsafe rebase2

### PR DESCRIPTION
**Pull request by raedwulf**
This pull-request does stack with my other two commits but it does split the commits on the branch so that it's easier to review/merge as you said you'd do when you have time.
I quickly checked that the tests do pass on each of the commits - so hopefully that will help :).

### CODE REVIEW

**Comment by raedwulf** [comment]
Don't pull this yet, I realised I missed a couple of things (my test-case fails).  I'll be rewriting the history to get some clean commits :) The first two commits, which are in the other pull-request, will remain unchanged.

**Comment by raedwulf** [comment]
I think this works now, but I'm still waiting for the travis builds to complete.  Feel free to review these commits.

**Comment by sustrik** [comment]
Would it be possible to get rid of ctxinit() and ctxterm()?

If there's thread-local "is_ctx_initialized" variable, each attempt to access the context could check it and initializa the context if it's false.

As for clean-up pthread_cleanup_push() could be used to do the deallocation.

**Comment by sustrik** [comment]
Anyway, the code looks good. When travis finishes, I'll merge it into the mainline.

**Comment by raedwulf** [comment]
I'm currently looking into getting rid of `ctxinit` and `ctxterm`.  It does require a check per API function, but that hopefully isn't too costly.  Using `pthread_key_create` as a thread destructor is clever :)

**Comment by raedwulf** [comment]
I'll have a pull-request with this later today :) It seems to work fine, I'm just testing to make sure the contexts are freed and am implementing C11 thread support properly so you can pass `./configure --enable-threads=c11` to make use of `_Thread_local` and the corresponding C11 thread functions instead of `pthread`.

**Comment by sustrik** [comment]
Is there a performance difference between pthreads and C11 version?

**Comment by raedwulf** [comment]
Shouldn't be much performance difference - the main reason is for future compatibility.  On second thought, I might hold off on the C11 support for now until there's better C11 implementations out there.  The only current implementations I'm aware of are pthread-wrappers and in musl but pthread is generally available everywhere.

I'm just finishing off my implementation of a `dill_atexit` which is thread-aware when threads are available.

**Pull request merged**
