### PR TITLE
Add automatic thread context creation and destruction

### PR DESCRIPTION
**Pull request by raedwulf**
Removes the need for the `ctxinit` and `ctxterm` functions.

### CODE REVIEW

**Comment by raedwulf** [comment]
It seems that Travis is having a large backlog of OS X builds again...

Could you review my latest changes and I'll tidy up the commits and recreate a new patch/pull request.

**Comment by raedwulf** [comment]
Also included in the comments in context.h:

The context is statically allocated in single-threaded builds, dynamically allocated in multi-threaded shared builds using `malloc`, and allocated using multiple thread locals in multi-threaded static builds.

- Single-threaded: This enables the compiler to remove the extra level of indirection in the case of the single-threaded build.
- Multi-threaded(shared): This enables the compiler to group TLS accesses (reduces `__tls_get_addr` calls.
- Multi-threaded(static): This enables the compiler to optimise TLS accesses into the least number of instructions (negligible difference in performance from single-threaded build).

**Comment by sustrik** [comment]
Looks good. Minor nits:

1. Rename context.h/.c to ctx.h/.c. Other filenames are abbreviations, so let's keep it consistent.
2. Review the copyright headers. There are new files where I am mentioned as copyright holder, which is not true.

**Comment by sustrik** [comment]
Ah, one more thing: Let's make the multi-threaded build the default.

The idea is that the default version -- which will be included in distros -- should provide maximum functionality. Those that want to super-optimize can build the library by hand.

**Comment by raedwulf** [comment]
Urgh, the build errors seems related to this: https://llvm.org/bugs/show_bug.cgi?id=7798

I'll modify the build scripts to try and work around it.

**Pull request closed without merging**
