### PR TITLE
Add documentation building support with pandoc

### PR DESCRIPTION
**Pull request by raedwulf**
Give this a go for building man pages - let me know if there are any issues!
It needs `pandoc` and `git` installed, downloads the gh-pages branch, and then proceeds to build the documentation.

### CODE REVIEW

**Comment by sustrik** [comment]
I am thinking of moving source files (.md) to master branch. What do you think?

**Comment by raedwulf** [comment]
I think that would be a good idea.  At the moment I modify the md files so that pandoc generates the output correctly so would you use the format used on the website or the one by pandoc?
Would the website then have a script or a git subrepository to get the pages?

**Comment by sustrik** [comment]
I would go for the format used for man pages.

The website can have a script to download the pages from master.

The idea is that anybody building libdill will get correct version of man pages in the generated package. The script to generate the website, on the other hand, will be run only when releasing a new version of libdill.

**Comment by sustrik** [comment]
Ok, I've copied the .md files into master branch (subdir man). Now the question is how to solve the chiken-and-the-egg problem when building the package.

The following came to my mind, but I am not sure it's the best possible way to do it:

1. Add a plain makefile (or shell script) into man subdirectory to generate man pages from md files
2. During `./configure` phase check for presence of pandoc and if present, run the said script.
3. In `make install` phase install the man pages, *if present*.
4. In `make dist` phase include the man pages into the package, *if present*.
5. In `make distclean` phase delete the man pages.

**Comment by raedwulf** [comment]
Unless there's a bug this is how the pull request does it currently (minus the downloading from gh-pages and conversion). 
We could also provide `--disable-docs` so that if pandoc is installed, a user does not need to head generate the docs but I'm not sure if this is necessary.

**Comment by raedwulf** [comment]
Rebased to match changes in HEAD (updated the Makefile scripts to do what you currently propose).  I've not implemented `--disable-docs` yet.  Whatever we end up with, this will be close to the final decision at any rate.

**Comment by raedwulf** [comment]
Okay, it looks like my version of pandoc has some flags that the Ubuntu used by travis does not have.
The reason I use those flags is to add the section headings and additional information through the Makefile.am build scripts as opposed to writing them directly within the man-page file.

Pandoc 1.12 is supported by their trusty beta servers, which is the minimum version of pandoc that my method works on.  I'll do that for now unless we try and figure out how the old versions of pandoc work.

**Comment by sustrik** [comment]
does it add manpages to the package during make dist?

**Comment by raedwulf** [comment]
Yes it does.  I'm just working on getting it to be tested with Travis (their trusty build servers are still experimental and they've not enabled the pandoc package in their container build servers yet).  I'll try building it using their sudo build servers.

Give me a sec (making the commits a bit cleaner) :)

**Comment by raedwulf** [comment]
Could you cancel the 7194d79 build? That's holding up travis and sadly pull-requesters have no control over it :(

**Comment by raedwulf** [comment]
Looks like it works :)

**Pull request merged**
