### PR TITLE
add detached coroutines

### PR DESCRIPTION
**Pull request by levkochetkov**
Those changes are handy to simplify resource managment and modeled after `ptherad_detach`.

### CODE REVIEW

**Comment by vlm** [comment]
@sustrik please consider this enhancement, hopefully it adds to the completeness of the libdill's resource model.

**Comment by sustrik** [comment]
Can you explain the use case? As I see it, coroutine either runs forever, in which case it doesn't matter whether it's attached or detached, or it does one thing and then finishes. However, in latter case detached coroutine is not guaranteed to finish (if process ends, it tears it down) which kind of defeats the purpose.

**Comment by vlm** [comment]
Imagine the web proxy service which spawns a coroutine for each HTTP request. Each HTTP request is getting handled by its own goroutine. Without `go_detach()` we would have to take notice of all the goroutine handles that are currently getting executed (the requests that are getting served) and make sure we `hclose()` them once the request finishes. With `go_detach()` we can do something like `go_detach(go(process_single_request))` and expect that all coroutine resources (such as stack) get deallocated once process is finished.

This is all more important because we don't have ready facilities to figure out the current handle for the current coroutine. If we had such a facility we could notify some other process about the new process which eventually requires hclose(). But that becomes very messy very quickly.

Therefore, a `go_detach()` is a nice way to avoid [stack] memory leaks in case we utilize a coroutine-per-request model.

**Comment by sustrik** [comment]
Ok, understood. Give me a day to think about that.

**Comment by sustrik** [comment]
Ok, so this opens a can of worms. But let's deal with it.

First, detached coroutine is killed forcefully when  process exists. There is no guarantee it will deallocate any system resources it uses (e.g. delete any temp files), send RST to a peer, flush data to a file etc. That severely limits its usefulness.

Given that the need for this functionality stems from the fact that doing all the orderly coroutine termination work (handshake with the parent etc.) is too much of a hassle, the problem would be at least alleviated if the terminal handshake was somehow automated.

The reason why libdill can't do this automatically is that it has no idea which coroutine own which other coroutines and thus, when shutting down, it has no idea which coroutines to terminate beforehand. (Note that terminating all coroutines which where created in current coroutine doesn't work. Child coroutine may be owned, say, by a network socket and the socket may have been passed to a different coroutine.)

In theory, something like Golang's defer() may work. Parent coroutine may hold a list of handles to close before it finishes:

```
coroutine void foo(void) {
    int cr = go(bar());
    deferred_close(cr);
    ...
} // bar is closed here
```
That still leaves a lot to be desired, but at least it can be a starting point for the discussion. Thoughts?

**Comment by vlm** [comment]
(This is not a proposal yet, just a bunch of thoughts).

## Coroutines hierarchy proposal

If parent coroutine has a list of handles to close, then if we can do this multiple times (from different coroutines), we'd have a race condition (several parents for a single handle). If we can only associate a coroutine with a parent a single time, that can be a tight nice implementation with intrusive lists, where a coroutine might either belong to some list of coroutines (attached to a parent), or not belong to any.

If we have such functionality, why not enable it by default? The coroutine spawned from a parent becomes attached to that parent and has to be terminated first before parent is fully terminated.

This looks like a nice solution, but now we need to consider two things:

 * Change of ownership — when a parent needs to exit but coroutines need to continue. The API can be straightforward: `int go_change_parent(hdl, new_parent_hdl);`
 * However, this doesn't seem like a trivial thing, because handle can be reused in a race:
```
int h = go(...); // h becomes attached to the current parent.
foobar(); // Something that changes content and can deallocate h which is attached to the parent.
go_change_parent(h, new_parent); // This might attach a wrong coroutine to a parent.
```

Therefore we can't just automatically garbage-collect coroutines even if they're attached to the parent. And if we don't garbage-collect them automatically on their exit, this loop becomes an eternal memory leak-generating tarpit:

```
while() {
    int fd = tcp_accept(); // new client
    deferred_close(go(process(fd));
}
```

## Resource management

On process termination, everything dies. Why do we care about some coroutines not finishing up? If we need to keep the list of coroutines to cancel, the process is free to do so. People understand `pthread` model where if you want something guaranteed, you have to account for all the threads and communicate with them. However, in many cases it is OK to just spawn them and let them finish on their own.

I am trying to understand why freestanding coroutines is a bad thing...

**Comment by sustrik** [comment]
+1 for the analysis.

As for why freestanding coroutines are a bad thing:

As already said, freestanding coroutine gives no guarantees on process shutdown. As you correctly note, users can take that into account and do the terminal handshake, but that also means that those cases don't require detached coroutines.

To look at it from a diffetent angle, the detached coroutine has no way to communicate with its parent coroutine (it can't be sure it is still running). However, it may make an assumption that its parent is the main coroutine as is thus always present. (When main coroutine finishes it tears down the entire process.)

The above means that detached coroutines are useful only if:

* They own no global resources to close.
* They are children of the main coroutine.

These hidden assumption are a trap of a kind. Imagine that years on your program becomes a legacy. A maintainer with no deep understanding of the code adds a creates a global resource from the detached coroutine. Resource leak will ensue. Alternatively, imagine they copy some code from the detached coroutine to a different coroutine that doesn't happen to be a child of main coroutine. The code starts crashing non-deterministically, depending on whether the parent coroutine is still running or not.

**Comment by paulofaria** [comment]
Just so you guys know. I implemented the concept of coroutine [groups](https://github.com/Zewo/Venice/blob/master/Sources/Venice/Coroutine.swift#L117-L265) in [Venice](https://github.com/Zewo/Venice). The use case is exactly the one you mentioned. A coroutine for each HTTP request being served.

We basically add coroutines to the group and when the coroutine finishes the group removes it automatically. And if `group.cancel` is called, we cancel all running coroutines.

The important thing I found out is that we can't remove the coroutine from inside the coroutine. So we [add finished coroutines to a list of finished coroutines](https://github.com/Zewo/Venice/blob/master/Sources/Venice/Coroutine.swift#L220) and we only remove it when [`addCoroutine`](https://github.com/Zewo/Venice/blob/master/Sources/Venice/Coroutine.swift#L212) or [`cancel`](https://github.com/Zewo/Venice/blob/master/Sources/Venice/Coroutine.swift#L247) is called in another moment. 

There's also the details that some coroutines might finish without yielding at all. So we only add coroutines to the group if they're still [running](https://github.com/Zewo/Venice/blob/master/Sources/Venice/Coroutine.swift#L226-L228) within the `addCoroutine` call.

We also can't use the handle itself to identify the finished coroutines, because we don't have access to the handle inside the coroutine. So we [create an internal identifier](https://github.com/Zewo/Venice/blob/master/Sources/Venice/Coroutine.swift#L215) for each coroutine added to the group.

I think this concept can be transported to `C` quite easily. It's working great for us. 😊

**Comment by paulofaria** [comment]
Here's the coroutine group being used in an HTTP server.

We [add](https://github.com/Zewo/Zewo/blob/2b6e4ba390276dd54abbbe03460b6588de593899/Sources/HTTP/Server/Server.swift#L124
) a coroutine to the group when a tcp connections is accepted, and on [stop](https://github.com/Zewo/Zewo/blob/2b6e4ba390276dd54abbbe03460b6588de593899/Sources/HTTP/Server/Server.swift#L94) we cancel all running coroutines in the group.

**Comment by robertjpayne** [comment]
I think one of the major issues (for me at least) is that right now `hclose` is very destructive. It not only closes child coroutines but also destroys open TCP streams that are somehow attached to the closed coroutine.

Take for instance this situation:

• HTTP Server spawns each request into it's own coroutine
• If the client connection drops it closes the coroutine (to clean up fast)
• The client request handler is running an HTTP request across a pool of TCP connections and is blocked on IO from the TCP connection

In this case an `hclose` on the coroutine managing the client request will destroy the TCP connection, this isn't possibly the end of the world for a HTTP client pool but for a Database pool this *really* sucks and there isn't a work around for this at all except to run the HTTP client pool over IPC which wouldn't be killed.

Hence my proposal about `hinterrupt` as `hclose` seems more suitable for complete shutdown than interrupting.

**Comment by sustrik** [comment]
The use cases here should be solved by the introduction of 'bundle' concept and using hdone() on the bundle to wait for the coroutines to finish. Feel free to re-open if there are use cases not yet covered.

**Pull request closed without merging**
